apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartcar-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartcar-frontend
  template:
    metadata:
      labels:
        app: smartcar-frontend
    spec:
      containers:
        - name: frontend
          image: tazmans/smartcar-frontend:0.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"

            limits:
              cpu: "200m"
              memory: "256Mi"
