version: "3.8"

services:
  frontend:
    image: tazmans/smartcar-frontend
    container_name: smartcar-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      API_URL: ${API_URL}

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
