apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartcar-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartcar-python
  template:
    metadata:
      labels:
        app: smartcar-python
    spec:
      containers:
        - name: python
          image: tazmans/smartcar-python:0.0.12
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: smartcar-python
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
