events {}

http {
  log_format smartcar
    '[$time_local] '
    '$remote_addr '
    '$request_method '
    '$uri '
    '$status '
    '$body_bytes_sent '
    '$request_time '
    '$upstream_addr';
  
  access_log /dev/stdout smartcar;
  error_log  /dev/stdout;

  gzip on;

  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;

  gzip_types
      text/plain
      text/css
      application/json
      application/javascript
      application/xml
      image/svg+xml;

  limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

  upstream backend_cluster {
    server backend:8080;
    server backend2:8080;
    server backend3:8080;
  }

  server {
    listen 80;

    add_header X-Project "SmartCar";

    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # add_header Content-Security-Policy "default-src 'self'" always;

    location / {
      proxy_pass http://frontend:80;
    }

    location /api/ {
      proxy_pass http://backend_cluster;

      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Host $host;

      limit_req zone=api_limit burst=10;
    }

    location /swagger/ {
      auth_basic "Restricted";

      auth_basic_user_file /etc/nginx/.htpasswd;

      proxy_pass http://backend:8080;
    }

  }
}