apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartcar-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartcar-backend
  template:
    metadata:
      labels:
        app: smartcar-backend
    spec:
      containers:
        - name: backend
          image: tazmans/smartcar-backend:0.0.5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: smartcar-backend
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
