apiVersion: v1
kind: Service

metadata: 
  name: smartcar-mosquitto

spec:
  selector:
    app: smartcar-mosquitto

  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 31883

  type: NodePort