---
- name: Install k3s agent
  hosts: worker
  become: true

  tasks:
    - name: Install k3s agent
      ansible.builtin.shell:
        cmd: >
          curl -sfL https://get.k3s.io |
          K3S_URL=https://{{ hostvars[groups['control_plane'][0]]['private_ip'] }}:6443
          K3S_TOKEN={{ hostvars[groups['control_plane'][0]]['k3s_node_token'] }}
          sh -
        creates: /usr/local/bin/k3s

    - name: Label worker nodes
      ansible.builtin.command:
        cmd: kubectl label node {{ hostvars[item]['ansible_hostname'] }} role=worker --overwrite
      loop: "{{ groups['worker'] }}"
      delegate_to: "{{ groups['control_plane'][0] }}"