apiVersion: v1
kind: Service

metadata:
  name: smartcar-postgres

spec:
  selector:
    app: smartcar-postgres

  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

  clusterIP: None