apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: smartcar-postgres

spec:
  serviceName: smartcar-postgres
  replicas: 1

  selector:
    matchLabels:
      app: smartcar-postgres

  template:
    metadata:
      labels:
        app: smartcar-postgres

    spec:
      containers:
        - name: postgres
          image: postgres:17
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: smartcar-config
                  key: DB_NAME

            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: smartcar-config
                  key: DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smartcar-secret
                  key: DB_PASSWORD

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi